### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by mynameisrufus** [pezra/hal-client#33]
I have a `/api` with:

```json
{
  "_links": {
    "self": {
      "href": "/api"
    },
    "curies": [
      {
        "name": "doc",
        "href": "/#{rel}",
        "templated": true
      }
    ],
    "doc:site": {
      "href": "/api/site"
    }
  }
}
```

When I call `rep.related('doc:site')` I get `KeyError: No resources are related via 'doc:site'`, what am I doing wrong?

**Comment by pezra** [comment]
Curies are expanded before lookups are attempted. So in your example it
would be `rep.related('/site')`. This protects clients from changes to the
curie prefix in the future. It would be nice if the raw rels were also
allowed though. Is certainly accept a PR to that effect.

Peter

**Comment by mynameisrufus** [comment]
Thanks, tidy lib! I will keep an eye out for relative urls.
