### ISSUE TITLE
Providing public Hash representation

### ISSUE THREAD

**Issue by quimrstorres** [pezra/hal-client#39]
Hey there,

What are your feelings about exposing the internal representation of a resource as a `Hash` (in `Representation` and `RepresentationSet`)? Or exposing only the properties bit of the representation as a `Hash`?

I am using `hal-client` to navigate through a JSON HAL API and build a component that abstracts away the consumption of such API. In order to return a business meaningful object to the clients of my component I need to access the properties of the HAL representation to create that object.

I understand that exposing the whole representation would be too much, but maybe it would make sense to expose only the properties as a `Hash`?

I see two ways of doing this:

- Create a `to_h` or `to_hash` method in representation that strips everything but the properties from `raw` and returns that `Hash`;
- Make the `Representation` object injectable, allowing users to provide their own implementation and possibly exposing the aforementioned functionality. This one would probably be a little tricky, since it would probably require some effort to identify all the things `Representation` (and probably `RepresentationSet` would need to implement) and establish a well-defined interface prepared for extension.

I can help if you think some of this makes sense.

Thanks,
Joaquim

**Comment by pezra** [comment]
I think the basic idea of a properties hash extraction method is solid. I don't love using `#to_h` or `#to_hash`, though, since there is a lot more to a representation than just the properties. Would a `#properties` method suffice?

I'd also be ok with a pluggable representation class, but that would be a bit more work. :smile:

**Comment by quimrstorres** [comment]
Yeah, sure! I suggested those methods but I think a `#properties` method would be much better. That would suffice for me. Want me to open a PR with it?

If I get the chance, I'll even prepare another patch with the injectable `Representation` to show you.

**Comment by pezra** [comment]
Sweet. A PR would be great.

**Comment by quimrstorres** [comment]
:+1:

**Comment by quimrstorres** [comment]
I will close this one and submit the patch as soon as possible. Thanks for sharing this, it is being really helpful :+1:
