### ISSUE TITLE
Navigate by related links using POST method

### ISSUE THREAD

**Issue by prodis** [pezra/hal-client#55]
I am facing a situation where I would need to navigate by related resources using POST method instead of GET method. 

I have this scenario:
```ruby
client = HalClient.new
items = client.get('http://myhalapi.com')
              .related('offers', args)
              .related('items')
```

And need to use something like that:
```ruby
client = HalClient.new
items = client.get('http://myhalapi.com')
              .related('offers', args, method: :post) # POST
              .related('items') # GET
```

I am sending a lot of information in query string in `offers` GET resource, specifically a big list of items in JSON format. For this amount of data is reasonable to make a POST request send the data in body. 

Do you think is it possible to implement this feature or another solution to solve this problem?

**Comment by pezra** [comment]
With hal-client you need to get a representation of a resource, via `#related`, before you can perform an unsafe method (PUT, POST, PATCH or DELETE) on the resource. Once you have gotten a `Representation` object you can call `#post`, `#put`, etc on it. Example:
 
```ruby
client
  .get('http://...')  # fetch API entry point
  .related('offers')  # lookup `offers` resource. This does *not* make an HTTP request. 
  .post(body)  # HTTP POST request is made
  .to_enum  # turn the standard HAL collection into an `Enumerable` of `HalClient::Representations`
```

Does that work for your situation?

**Comment by prodis** [comment]
I will try it. Thanks!

**Comment by prodis** [comment]
@pezra It worked!
Thank you!
