### ISSUE TITLE
hal-client never reuses client instances and always creates new connections

### ISSUE THREAD

**Issue by ivoanjo** [pezra/hal-client#56]
I was profiling a JRuby app which makes heavy use of hal-client and noticed that a lot of time was spent creating connections. That seemed rather strange to me as we initialize hal_client with a `:base_client` using an `HTTP::Client` instance configured for persistent connections.

Debugging it a bit led me to the `client_for_post` and `client_for_get` functions:

```ruby
  def client_for_get(options={})
    override_headers = options[:override_headers]

    if !override_headers
      @client_for_get ||= base_client.with_headers(default_message_request_headers)
    else
      client_for_get.with_headers(override_headers)
    end
  end
```

In both functions, a new client is created if custom headers are passed, instead of the existing one being used. But I wasn't passing any custom headers in. But if you look at the caller:

```ruby
  def get(url, headers={})
    headers = auth_headers(url).merge(headers)
    client = client_for_get(override_headers: headers)
    # ...
  end
```
with `auth_headers` being

```ruby
  def auth_headers(url)
    if h_val = auth_helper.call(url)
      {"Authorization" => h_val}
    else
      {}
    end
  end
```
This means that there's absolutely no way for `headers` to ever be `nil`. It will always at least be an empty hash. And thus, the base client is always ignored and a new client is created every time.

**Comment by pezra** [comment]
Good catch. That is definitely a bug. I'd happily merge a PR to fix it.

**Comment by ivoanjo** [comment]
I'll be glad to try to tackle this :)

Do you think replacing `if !override_headers` with `if !override_headers || override_headers.empty?` is enough? Or do you think it's useful to preserve the option for clients to explicitly use empty headers---and thus we would need to distinguish between empty override headers requested by clients vs empty override headers because no override headers were specified at all.

**Comment by pezra** [comment]
I imagine that override headers are often reused. Maybe we should memoize
the client into a hash keyed on the override headers.
