### ISSUE TITLE
SSL URLs

### ISSUE THREAD

**Issue by rbetancor** [pezra/hal-client#69]
How to use the HalClient gem with ssl urls? ... does someone have an example of that?.

I've tryed to pass a options: {ssl: {client_ke: key, client_cert:cert,verify:false}}  to the get method ... but no luck.

**Comment by rbetancor** [comment]
Example for the records:

```
cert = OpenSSL::X509::Certificate.new File.read(cert_file)
key = OpenSSL::PKey::RSA.new File.read(key_file)
client = HTTP::Client.new({ ssl: {key: key,cert: cert,verify_mode: 0}})
hal_client = HalClient.new(base_client: client)
```

**Comment by pezra** [comment]
Glad you found the way to make that work. 👍
