### ISSUE TITLE
Missing Examples

### ISSUE THREAD

**Issue by rbetancor** [pezra/hal-client#70]
Do someone have a bunch of examples on how to use the gem?

I'm more used to the dev technique of CPCU (Copy Paste Change and Use)  :-)

I'm trying to use the HalClient to access a API, but I have no luck using it, that what I did so far:

```
# load the SSL cert and key
cert = OpenSSL::X509::Certificate.new File.read(cert.pem')
key = OpenSSL::PKey::RSA.new File.read('key.pem')
# client instance
client = HTTP::Client.new({ ssl: {key: key,cert: cert,verify_mode: 0}})
hal=HalClient.new(base_client: client)

# Now point to Subscribers resource
subscribers = hal.get('https://api.server.tld:1443/api/subscribers')

```

Till that point, everything perfect ... but now, how do I iterate over the elements of the resouce collection, the reply of the API server have and _embedded section with the first 10 entries of the collection with all their attributes, only one attribute "total_count", and a links sections like this:

```
 "_links"=>
  {"curies"=>{"href"=>"http://purl.org/sipwise/ngcp-api/#rel-{rel}", "name"=>"ngcp", "templated"=>true},
   "next"=>{"href"=>"/api/subscribers/?page=2&rows=10"},
   "ngcp:subscribers"=>
    [{"href"=>"/api/subscribers/52"},
     {"href"=>"/api/subscribers/55"},
     {"href"=>"/api/subscribers/59"},
     {"href"=>"/api/subscribers/63"},
     {"href"=>"/api/subscribers/67"},
     {"href"=>"/api/subscribers/71"},
     {"href"=>"/api/subscribers/75"},
     {"href"=>"/api/subscribers/79"},
     {"href"=>"/api/subscribers/83"},
     {"href"=>"/api/subscribers/87"}],
   "profile"=>{"href"=>"http://purl.org/sipwise/ngcp-api/"},
   "self"=>{"href"=>"/api/subscribers/?page=1&rows=10"}},

```
I want to be able to do something like:

`subscribers.each do |sub| puts sub.uuid end`

But I get:

`NoMethodError: undefined method `each' for #<HalClient::Representation:0x0055abaeb107d8>`

So, some examples would help a lot.

**Comment by rbetancor** [comment]
The far I have get is:

`subscribers.related('ngcp:subscribers').to_enum.each do |sub| puts sub['uuid'] end`

But that only return me the uuid of the first 10 results that was embedded in the get reply, it doesn't iterate over the whole collection.

**Comment by pezra** [comment]
@rbetancor, that representation is a nice HAL doc but you'll have to roll your own iteration because it doesn't follow [the standard for hypermedia collections](https://tools.ietf.org/html/rfc6573).  Maybe something like the following:

```ruby
subscriber_ids = Enumerator.new do |yielder|
  while true do
    subscribers
      .related('ngcp:subscribers')
      .map{|sub| sub['uuid'] }
      .each{|uuid| yielder << uuid}
    subscribers = subscribers.related("next").first
  rescue KeyError
    # the end
  end
end

subscriber_ids.each do |id| puts id end
```
