### ISSUE TITLE
`item` relation required by Collection?

### ISSUE THREAD

**Issue by prognostikos** [pezra/hal-client#74]
Hello,

I'm new to HAL and Hal-Client. I noticed that the Collection class will only pass an element of the collection to the each block if it has an `item` relation. This was preventing the element from being sent to the block in an API that I was trying to use. When I changed Collection to look for `self` instead of `item` I was able to iterate through the collection as I expected to be able to.

Looking at [the spec](https://tools.ietf.org/html/draft-kelly-json-hal-08) I can't find any mention of `item`, though `self` is mentioned.

Have I run into an edge case with a broken HAL API or is this a problem that others have experienced?

Very much a newb here, so any clarification would be appreciated.

**Comment by pezra** [comment]
The `item` rel is defined in [RFC 6573](https://tools.ietf.org/html/rfc6573) which specifies a standard for paged collections. It is not part of HAL, but rather part of the large set of internet standards.

I don't think it is an edge case or a broken API. It seems like you are looking at a representation that is not a collection. Not all representations are collections and that is OK.
